### ISSUE TITLE
tutorial_cartesian-interface/smoke-test failed on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by iskanderuse** [icub-training/icub-training.github.io#2] opened 2019-02-04 13:54 UTC
I've got this error after all installation steps on Ubuntu 18.04.1 LTS:

```sh
Test suite Test Tutorial Cartesian Interface started...
[INFO]  (Test Tutorial Cartesian Interface) reports: yarpmanager is setting up the fixture...
[ERROR] (Test Tutorial Cartesian Interface) asserts error on (ret) with exception: yarpmanager (run) cannot setup the fixture because Failed to run tutorial_cartesian-interface on testnode. (State: 5, parameter: ) cannot ask /testnode to check for status of tutorial_cartesian-interface (Blocked in broker semaphor)  due to (SendMsg) disconnecting from /testnode Failed to run iKinCartesianSolver on testnode. (State: 5, parameter: --context simCartesianControl --part left_arm) cannot ask /testnode to check for status of iKinCartesianSolver (Blocked in broker semaphor)  due to (SendMsg) disconnecting from /testnode cannot ask /testnode to check for status of iKinCartesianSolver (Blocked in broker semaphor)  due to (SendMsg) connecting to /testnode Failed to run yarprobotinterface on testnode. (State: 5, parameter: --context simCartesianControl --config no_legs.xml) cannot ask /testnode to check for status of yarprobotinterface (Blocked in broker semaphor)  due to (SendMsg) connecting to /testnode cannot ask /testnode to check for status of yarprobotinterface (Blocked in broker semaphor)  due to (init) checking existence of /testnode Failed to run iCub_SIM on testnode. (State: 5, parameter: ) cannot ask /testnode to check for status of iCub_SIM (Blocked in broker semaphor)  due to  cannot ask /testnode to check for status of iCub_SIM (Blocked in broker semaphor)  due to  cannot ask /testnode to check for status of iCub_SIM (Blocked in broker semaphor)  due to  cannot run tutorial_cartesian-interface on testnode : Timeout while waiting for some resources. /icubSim/cartesianController/left_arm/state:o does not exist cannot run iKinCartesianSolver on testnode : Timeout while waiting for some resources. /icubSim/left_arm/state:o does not exist /icubSim/torso/state:o does not exist cannot run iCub_SIM on testnode : cannot run iCub_SIM on /testnode cannot run yarprobotinterface on testnode : Timeout while waiting for some resources. /icubSim/right_arm/state:o does not exist /icubSim/left_arm/state:o does not exist /icubSim/torso/state:o does not exist 
[INFO]  (Test Tutorial Cartesian Interface) reports: yarpmanager is tearing down the fixture...
Test suite Test Tutorial Cartesian Interface failed!

---------- summary -----------
Total number of test suites  : 1
Number of passed test suites : 0
Number of failed test suites : 1
Total number of test cases   : 0
Number of passed test cases  : 0
Number of failed test cases  : 0
```

**Comment by pattacini** [comment] 2019-02-04 15:03
Thanks @iskanderuse for reporting.
Let's try then to run the tutorial step by step.

### 1. Build
Go into `tutorial_cartesian-interface` directory and do:
```sh
$ mkdir build && cd build
$ cmake ../
$ make install
```
Check that the binary gets installed correctly by doing:
```sh
$ which tutorial_cartesian-interface
```
whose output should be something like `$ROBOT_INSTALL/bin/tutorial_cartesian-interface`.

### 2. Launch yarpserver
```sh
$ yarpserver --write
```
It might be that yarp infrastructure doesn't run correctly since from the error above `yarpmanager` seems not able to talk to the `testnode`.
You could verify that by asking:
```
$ yarp where
```
which will return the IP address of the machine where the server will be running.

### 3. Launch the tutorial
From a second console launch the `yarpmanager` GUI:
```sh
$ yarpmanager
```
that will look like this:

![fig-0](https://user-images.githubusercontent.com/3738070/52215674-d8423800-2894-11e9-9f32-397087582b64.jpg)

Notice the two applications listed on the left:
- `Tutorial_on_Cartesian_Interface_System`
- `Tutorial_on_Cartesian_Interface_App`

Double click on the `System` application and launch the corresponding modules by clicking on the **Run** button (top green button on the left vertical tab).

![fig-1](https://user-images.githubusercontent.com/3738070/52215972-864de200-2895-11e9-9208-6d1e6bb008e1.jpg)

Wait until all the modules warm up correctly (having the green light). Finally, double click on the `App` and launch the tutorial as illustrated above.

![fig-2](https://user-images.githubusercontent.com/3738070/52216005-982f8500-2895-11e9-9f6e-99ff5ba28327.jpg)

Did you find anything gone wrong while proceeding through these steps?

**Comment by iskanderuse** [comment] 2019-02-04 19:59
according to your instructions, everything went as expected. no errors

**Comment by pattacini** [comment] 2019-02-04 21:12
Good that's working 👍 

The differences between the steps above and smoke-test are:
- smoke-test does employ the `yarprun` broker instead of the `localhost`.
- smoke-test runs a dedicated application containing all modules with some wait states to ensure a good start.
- smoke-test also launches a corollary test (of course) to check some properties of the trajectory.

Then, I would proceed as follows:
1. Build and install as above.
1. Launch `yarpserver` as above.
1. Launch the `yarprun` broker:
    ```sh
    $ yarprun --server /testnode
    ```
1. Launch the `yarpmanager` GUI as above.
1. From within the `yarpmanager`: open file ➡️ load `tutorial_cartesian-interface/smoke-test/fixtures/fixture.xml`.

Now, you can launch all the modules at once: they should run correctly because internally in the xml the wait states are enforced.

If you'll get errors, (force) stop everything and run the modules one after another, starting from the very first (`iCub_SIM`) and then going down, always waiting until the current module has the green light. To do this, just right-click on the single module and select `Run`. This way, you'll somehow add up manually further wait states in case the original ones are not sufficient. 

Also, you might want to play with the internal wait states. The fixture has the following three wait states that you can try to increase keeping always the last one as the biggest:
- [`yarprobotinterface` wait state][1]
- [`iKinCartesianSolver` wait state][2]
- [`tutorial_cartesian-interface` wait state][3]

[1]: https://github.com/vvv-school/tutorial_cartesian-interface/blob/master/smoke-test/fixtures/fixture.xml#L21
[2]: https://github.com/vvv-school/tutorial_cartesian-interface/blob/master/smoke-test/fixtures/fixture.xml#L33
[3]: https://github.com/vvv-school/tutorial_cartesian-interface/blob/master/smoke-test/fixtures/fixture.xml#L43

Once you'll have got a stable set of wait states, it could be the time to give the smoke-test another whirl 🤞 

Those default values are generally ok for a VM but, obviously, do depend on how fast modules can start up on the specific machine.

**Comment by iskanderuse** [comment] 2019-02-05 09:27
Something is wrong in my installation. Following http://wiki.icub.org/wiki/Check_your_installation
the command ` iCub_SIM` in terminal ends with "segmentation error".

**Comment by pattacini** [comment] 2019-02-05 10:37
@iskanderuse do you mean that `iCub_SIM` does seg-fault upon closure or, instead, that you're unable to run it correctly since the seg-fault happens right after the launch?

As you went through the steps detailed in https://github.com/icub-training/icub-training.github.io/issues/2#issuecomment-460280888, we tend to assume that you managed to run `iCub_SIM` from the `yarpmanager`.

**Comment by iskanderuse** [comment] 2019-02-05 12:42
Sorry for misunderstanding! In #2 I did not launch the app. The tutorial doesn't launch.

**Comment by vtikha** [comment] 2019-02-05 14:39
@iskanderuse could you please run the `iCub_SIM` and post the terminal output here?

**Comment by iskanderuse** [comment] 2019-02-05 14:49
Here's the [output-log.txt](https://github.com/icub-training/icub-training.github.io/files/2832983/output-log.txt).

**Comment by pattacini** [comment] 2019-02-06 10:53
While we will be looking carefully into the possible causes, could you please do the following:
```sh
$ yarp-config context --import simConfig iCub_parts_activation.ini
```
This way, you'll import the file `iCub_parts_activation.ini` into `~/.local/share/yarp/context/simConfig` in order to be able to edit it.

Finally, edit `iCub_parts_activation.ini` by switching off all the flags of the group `[PARTS]`.

This check will allow us to verify whether the problem is caused by the underlying YARP controlboard wrappers. If the parts are switched off, then the simulator will start up at least even though it will not be possible to move it.

Hopefully, this test will let us narrow down the issue.

**Comment by iskanderuse** [comment] 2019-02-06 14:45
I switched off all parts. Simulator started.

**Comment by pattacini** [comment] 2019-02-06 15:14
Ok, then let's try to inquire if YARP is behaving correctly underneath.

To do so, we need to enable a testing component that we didn't ask you to compile 'till now. Its name is `fakeMotionControl` and, to compile it, just follow these [modified instructions][1] in the wiki.

Once built and installed, you'll be able to list it down by doing:
```sh
$ yarpdev --list | grep -i fakemotioncontrol
```

Here's the command to launch the component:
```sh
$ yarpdev --device fakeMotionControl --name /fake
```

You should now see a bunch of YARP ports opnened up by `fakeMotionControl`:
```sh
$ yarp name list | grep -i fake
```

Finally, let's log the output of a specific port:
```sh
$ yarp read /tmp /fake/state:o
```

As a result, you should be reading an endless list of `0.0`.

[1]: https://github.com/icub-training/icub-training.github.io/wiki/Installation/_compare/596a4f2213828b50523f567b1d1ec5a7a0ce5ca3

**Comment by iskanderuse** [comment] 2019-02-06 20:26
That's what I got:

```
$ yarpdev --list | grep -i fakemotioncontrol
[INFO]Device "fakeMotionControl", available on request (found in /home/iskanderuse/robot-install/lib/yarp/yarp_fakeMotionControl.so library), wrapped by "controlboardwrapper2".

```

```
$ yarp name list | grep -i fake
registration name /fake/command:i ip 192.168.0.12 port 10003 type tcp
registration name /fake/quit ip 192.168.0.12 port 10006 type tcp
registration name /fake/rpc:i ip 192.168.0.12 port 10002 type tcp
registration name /fake/state:o ip 192.168.0.12 port 10004 type tcp
registration name /fake/stateExt:o ip 192.168.0.12 port 10005 type tcp

```
```
$ yarp read /tmp /fake/state:o
yarp: Port /tmp active at tcp://192.168.0.12:10007/
yarp: Receiving input from /fake/state:o to /tmp using tcp
0.0
0.0
...
```

**Comment by pattacini** [comment] 2019-02-07 09:02
Thanks @iskanderuse for the test and the patience.
Our last resort is to do wild debugging. To do so you could:
- rebuild `yarp` and `icub-main` specifying **`-DCMAKE_BUILD_TYPE=Debug`** instead of `Release`
- launch `yarpserver`
- launch the debugger:
    ```sh
    $ gdb iCub_SIM
    (gdb) run
    ```
- report back on the error output

Another possibility would be to perform remote assistance by means of e.g. `Teamviewer` or we will be troubleshooting all these issues Monday morning.

**Comment by iskanderuse** [comment] 2019-02-07 16:16
[output2.txt](https://github.com/icub-training/icub-training.github.io/files/2841720/output2.txt)

**Comment by pattacini** [comment] 2019-02-07 16:55
I've noticed from the log that the parts are still switched off. See below:
```
 Elevation :  off 
 startHomePos :  on 
 Legs :  off 
 Torso :  off 
 Left arm :  off 
 Left hand :  off 
 Right arm :  off 
 Right hand :  off 
 Head :  off 
 Fixed Hip :  off 
```

You should first edit the file `~/.local/share/yarp/context/simConfig/iCub_parts_activation.ini` to enable all parts again and then start over the debug.

**Comment by iskanderuse** [comment] 2019-02-08 09:32
Output with enabled parts:
[output3.txt](https://github.com/icub-training/icub-training.github.io/files/2844445/output3.txt)

**Comment by pattacini** [comment] 2019-02-09 14:37
@iskanderuse the log is not informative enough to draw any conclusion, unfortunately.
We will look into this in person on Monday morning.

**Comment by pattacini** [comment] 2019-02-11 10:25
A VM was used as a backup.
Closing; feel free to open it again in case needed.

**Closed as completed by pattacini** 2019-02-11 10:25 UTC
Labels: 👋 help wanted, 💻 installation
